### PR TITLE
Neon CFLAGS for RPI2

### PR DESCRIPTION
**Pull request by NF3RN0**
CFLAGS += -mfpu=neon

### CODE REVIEW

**Comment by gizmo98** [comment]
The intention was 'let the user pass CFLAGS with -mfpu=neon'. The rpi2 supports -mfpu=neon-vfp4. But this flag is not backward compatible with cortex-a8 or cortex-a9 cores.

**Comment by ricrpi** [comment]
@gizmo98 

If the user passes in CFLAGS then the whole of CFLAGS will need to be passed in as the makefile doesn't use (overridable?) to add to it. Not got the brain power at the minute to fix this issue.

**Comment by gizmo98** [comment]
Sorry. RetroPie-Setup uses OPTFLAGS to pass this information.

**Comment by ricrpi** [comment]
actually I can use OPTFLAGS too to fix this. Does RetroPie also pass in '-flto' for OPTFLAGS because it will be overridden within the makefile.

**Comment by ricrpi** [comment]
@NF3RN0 I have defined OPTFLAGS within RaspbianList_Pi2 so when using the build script, you should now get -mfpu=neon passed into the compiler.

**Comment by gizmo98** [comment]
Yeah. Link to optimization flag will be overridden. Have you tested if the plugin runs faster with -flto?

**Comment by ricrpi** [comment]
Afraid not and can't test at the moment - working away from home and ssh fails to connect.

**Pull request merged**
