### PR TITLE
RPI2 Rework

### PR DESCRIPTION
**Pull request by gizmo98**
Raspberry PI 2 is no longer "armv6l" (it is "armv7l"). An option is more flexible as a hard coded MACHINE test. So we can use this plugin on other broadcom platforms as well. I have not removed ("$(MACHINE)","armv6l") because it would break backward compatibility with your mupen64plus build script.

If NEON=1 is set gles2n64 compiles with arm neon optimizations. 

I also added the option "multisampling". Mario64 looks and runs nice on a RPI2 with multisampling=2.

### CODE REVIEW

**Comment by gizmo98** [comment]
@ricrpi 
Thanks! Please merge the other PRs as well so we can use your repos with PI2.

**Comment by ricrpi** [comment]
@gizmo98 
Can't see any other PRs to merge...

**Comment by gizmo98** [comment]
@ricrpi 
Could you please merge these PRs?
https://github.com/ricrpi/mupen64plus-video-gles2rice/pull/4
https://github.com/ricrpi/mupen64plus-core/pull/3
https://github.com/ricrpi/mupen64plus-audio-omx/pull/1

**Comment by ricrpi** [comment]
@gizmo98 

all merged, I've not tested but assume they will still support Pi B.

**Comment by gizmo98** [comment]
Thank you very much! The commits should be backwards compatible. I will test if RetroPie-Setup works with __platform=rpi1 and __platform=rpi2. RPI2 is really fast. Compilation of all plugins takes only 10-15 minutes now.

**Comment by gizmo98** [comment]
Checked! target rpi1 and rpi2 compile and run without any error. Do you mind if do more PRs? I like to add a fullscreen ini "option" (gles2n64) and add some game compatibility options in RiceVideoLinux.ini.

BR
gizmo

**Comment by ricrpi** [comment]
@gizmo98 I've added you as a collaborator to all my mupen64plus forks. Given all your hard-work and my lack of time to keep up with all the current developments it will be easier for all. 

Do you know if the official release of the core now works on the pi?

**Comment by gizmo98** [comment]
Thank you very much!

The official release is working now. I used your ric_dev branch and ported the necessary vfp hard float and video core parts. It is necessary to add flags "make VFP_HARD=1 VC=1..." (rpi1) or "make NEON=1 VC=1..." (rpi2).

**Comment by ricrpi** [comment]
What are your thoughts on using the ricrpi master branch as a stable fork for the pi? 

There are alot of developments going on and I'm a little concerned the official release may get temporarily broken on ARM (due to development being done for X86 first then ported). 

My plan is to continue work on a new dynamic recompiler but great to hear the official release works now

**Comment by gizmo98** [comment]
I was just curious to see if the official release is working. And i was surprised how well it runs. In my opinion your fork runs a little bit faster. So as long the official release is not on par, more compatible or has any other advantage RetroPie-Setup will use your repo.

**Comment by ricrpi** [comment]
I think there are some 'emulated DMA' optimizations I need to push upstream but can't think of anything else that makes mine faster.

**Pull request merged**
